Bug 1993083 - Vendor libwebrtc from 503422d3ab
Upstream commit: https://webrtc.googlesource.com/src/+/503422d3ab9f73cce7b79ec5c29b0c6dfee6d6ce
    IWYU rtc_base/type_traits

    which otherwise fails with clang modules enabled via
      use_clang_modules = true
    and the following error message:
    ../../rtc_base/type_traits.h:27:45: error: declaration of 'declval' must be imported
      from module 'std_core.utility_core.declval' before it is required
       27 |           std::is_convertible<decltype(std::declval<C>().data()), T*>::value &&
          |                                             ^

    Bug: webrtc:42226242
    Change-Id: Ic5785f51d2335ac0fa93fdc6eb4bd1e1fb219c76
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/401880
    Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
    Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
    Reviewed-by: Harald Alvestrand <hta@webrtc.org>
    Cr-Commit-Position: refs/heads/main@{#45208}